### ISSUE TITLE
Provide a C# version

### ISSUE THREAD

**Issue by paulroho** [dtanzer/babystepstimer#2]
To also attract the .Net-crowd to this interesting example, a C#-version would be great. 
BTW, I volunteer for creating it. PR to come.

**Comment by dtanzer** [comment]
That would be awesome, looking forward to the PR!
If you want, update the README with your contact info (add a "Contributors" section or something like that).

**Comment by paulroho** [comment]
A strategic question:
You start off using a single file leveraging an awt JFrame. The best corresponding thing to this on the .NET platform would probably be the WinForms library. Although one could code similar to the original example, probably almost nobody would have, rather than using some designer supported approach using Visual Studio's RAD capabilities. Of course then, just coding in a single messy code behind file could be done (and has been many times). Also, the approach using the HTML based UI (over separate native controls) feels rather artificial to the platform.

So the question is, would you prefer sticking to the approach from the Java sample (no designer used, HTML based UI) or would you be fine starting off with a more idiomatic mess?

**Comment by dtanzer** [comment]
Does the updated "Contributors" section in the README.md answer your strategic questions?

**Comment by paulroho** [comment]
Yes, "may (or may not)" says it all. :)
